# auth2配置

# jpa配置 数据源配置
spring:
  datasource:
    url: ${base.mysql.url}/keycabinet?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123.com
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: Taroco-OAuth2-HikariCP
  #redis配置
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: cn.taroco.*.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

taroco:
  # swagger2配置
  swagger:
    enabled: true
    title: 钥匙柜管理系统(keycabinet)
    description: 钥匙柜管理系统(keycabinet) RestFull Api
    version: 2.0.1-SNAPSHOT
    license: Apache License, Version 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    terms-of-service-url:
    contact:
      name: lumiing
      url:
      email:
    base-package: cn.taroco.keycabinet.controller
    base-path: /**
    exclude-path: /error